dataset:
  # txt格式 包含所有完整图片路径
  train_dataset_file_path: D:\Users\Desktop\train\train.txt
  val_dataset_file_path: D:\Users\Desktop\train\val.txt
  train_batch_size: 32
  train_num_workers: 8
  val_batch_size: 8
  val_num_workers: 2

transform:
  input_size: [ 24, 94 ]

model:
  # 网络最后输出形状
  class_num: 68
  pretrained_model_path: ""

train:
  train_epochs: 200
  freeze:
    is_use: True
    epochs: 50
  warmup:
    is_use: True
    epochs: 10
    start_learning_rate: 0.001
  learning_rate: 0.005
  momentum: 0.9
  lr_schedule:
    is_use: True
    max: 150

result:
  log_dir: "./logs"
  metrics_dir: "./metrics"
  save_dir: "./models"











